service: superlock

provider:
  name: aws
  runtime: nodejs6.10
  environment:
    MONGODB_URI: ${file(./config.yml):MONGODB_URI}

functions:
  createUser:
    handler: handler.createUser
    events:
      - http:
          path: user
          method: post
          cors: true

  updateUser:
    handler: handler.updateUser
    events:
      - http:
          path: user/{id}
          method: patch
          cors: true

  fetchUserById:
    handler: handler.fetchUserById
    events:
      - http:
          path: user/{id}
          method: get
          cors: true

  fetchUsers:
    handler: handler.fetchUsers
    events:
      - http:
          path: user
          method: get
          cors: true

  destroyUser:
    handler: handler.destroyUser
    events:
      - http:
          path: user/{id}
          method: delete
          cors: true

  createSheet:
    handler: handler.createSheet
    events:
      - http:
          path: sheet
          method: post
          cors: true

  fetchSheetById:
    handler: handler.fetchSheetById
    events:
      - http:
          path: sheet/{id}
          method: get
          cors: true
  
  fetchSheets:
    handler: handler.fetchSheets
    events:
      - http:
          path: sheet
          method: get
          cors: true
  
  updateSheet:
    handler: handler.updateSheet
    events:
      - http:
          path: sheet/{id}
          method: patch
          cors: true

  destroySheet:
    handler: handler.destroySheet
    events:
      - http:
          path: sheet/{id}
          method: delete
          cors: true